version: '3.7'

services:

  nginx:
    build:
      context: .
    image: dainst/dai-lens
    environment:
      PORT: 80
    networks:
      - web
    volumes:
      - repository:/usr/share/nginx/html/repository
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:lens.idai.world"
        - "traefik.port=80"

volumes:
  repository:
    name: lens_repository
    external: true

networks:
  web:
    external: true
