version: '3.7'

services:

  nginx:
    build:
      context: .
    image: dainst/dai-lens
    ports:
      - "8080:80"
    volumes:
      - ./repository:/usr/share/nginx/html/repository
    environment:
      PORT: 80
